# tentuin base image
FROM python:3.9

# step 1
# install fastapi and uvicorn
RUN pip install fastapi "uvicorn[standard]"

# step 2
# siapin kodingan (folde project, main file)
WORKDIR /app
COPY  . .

# expose port
EXPOSE 8080

# step 3
# execute file
CMD ["uvicorn", "api:app", "--host", "0.0.0.0", "--port", "8080", "--reload"]

# command to up dockerfile to hub.docker.com
# docker build -t <username>/<repo>:<tag> .
# docker push gilbertk27/test-fastapi:1.0
# docker tag fastapi:1.0 gilbertk27/test-fastapi:1.0