version: "3"

services: 
  api:
    ports:
      - "3003:8080"
    container_name: fastapi-container
    image: gilbertk27/test-fastapi:1.0

  postgres:
    image: postgres:13.2 # kalau no version otomatis pake latest
    ports: 
      - "5450:5432"
    container_name: postgres-container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mainDB